############################
#  TG-SHOP  docker-compose #
############################

services:
  ##################################################################
  # PostgreSQL
  ##################################################################
  postgres:
    image: postgres:15
    container_name: psgr
    restart: always
    env_file:
      - .env                       # POSTGRES_DB / USER / PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg-shop-net

  ##################################################################
  # Django + Gunicorn
  ##################################################################
  web:
    build: ./shop_tg_app          # Dockerfile находится в подпапке
    image: hurtki/tg-shop:latest
    container_name: tg-shop-django
    restart: always
    env_file:
      - .env                      # .env с переменными окружения
    depends_on:
      - postgres
    networks:
      - tg-shop-net
    ports:
      - "8000:8000"               # оставляем наружу только для дебага
    volumes:
      # cтатика-медиа на хосте, чтобы nginx читал напрямую
      - ./shop_tg_app/static:/app/www/shop_tg_app/static
      - ./shop_tg_app/media:/app/www/shop_tg_app/media
      # (не монтируем logs, т.к. Gunicorn пишет в STDOUT)

  ##################################################################
  # Nginx (обслуживает 80 → web:8000)
  ##################################################################
  nginx:
    image: nginx:latest
    container_name: tg-shop-nginx-server
    restart: always
    depends_on:
      - web
    networks:
      - tg-shop-net
    ports:
      - "80:80"                   # HTTP; HTTPS добавите позже, когда будет домен
    volumes:
      # наш конфиг
      - ./nginx/tg-shop.conf:/etc/nginx/conf.d/tg-shop.conf:ro
      # «глушим» дефолтный конфиг, чтобы не видеть Welcome-страницу
      - /dev/null:/etc/nginx/conf.d/default.conf
      # статика и медиа, чтобы nginx обслуживал напрямую
      - ./shop_tg_app/static:/app/www/shop_tg_app/static:ro
      - ./shop_tg_app/media:/app/www/shop_tg_app/media:ro
      # логи nginx → общий каталог проекта
      - ./shop_tg_app/logs:/app/www/shop_tg_app/logs

volumes:
  postgres_data:

networks:
  tg-shop-net:
    driver: bridge